[package]
name = "e07_point_cloud_renderer"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
ash = "0.38.0"
framework = { version = "0.1.0", path = "../framework" }
glam = "0.32.1"
image = { version = "0.25.9", default-features = false, features = ["png", "jpeg"] }

[[bin]]
name = "07_PointCloudRenderer"
path = "src/main.rs"
