[workspace]
resolver = "3"
members = [
    "e00-my-gpu",
    "e01-hello-gpu",
    "e02-uniform-buffer",
    "e03-storage-buffer",
    "e04-copying",
    "e05-edge-detector",
    "e06-atomics",
    "e07-point-cloud-renderer",
    "e08-shared-memory",
    "e09-matrix-multiplication",
    "framework"
]

