#version 450

// Activate the required extension GL_EXT_debug_printf
#extension GL_EXT_debug_printf: require

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;
void main()
{
	// TODO: Print a message, with debugPrintfEXT, using 
	// gl_GlobalInvocationID.x to identify different threads doing the work.
    if (gl_GlobalInvocationID.x == 0)
    {
        debugPrintfEXT("hello from %u", gl_GlobalInvocationID.x);
    }
}